language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
- npm i -g yarn
- yarn
- yarn build
addons:
  ssh_know_hosts: vdorchan.com
script:
- rsync -avu --progress --delete dist/ root@vdorchan.com:/srv/www/vdorchan.com/
before_install:
- openssl aes-256-cbc -K $encrypted_3dac2b527684_key -iv $encrypted_3dac2b527684_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
